spring:
  config:
    activate:
      on-profile: dev


  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
      username: admin
      password: pass
      authentication-database: admin
      auto-index-creation: true

mercado-pago:
  pix:
    server: ${URL:https://api.mercadopago.com}
    accessToken: ${ACCESS_TOKEN:Bearer APP_USR-4013374519233343-062409-dc7e9d40ecf05a013ad8c3be4f018821-241014275}

server:
  port: 8083

aws:
  config:
    region: ${AWS_SQS_REGION:us-east-1}
    accessKey: ${AWS_SQS_ACCESS_KEY:AKIA6ODU3YWAJQBOFFE3}
    secretKey: ${AWS_SQS_SECRET_KEY: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}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
          multiplier: 1
          max-interval: 300000

rabbitmq:
  payment-status-exchange: ${PAYMENT_STATUS_EXCHANGE:payment-status.ex}
  payment-aproved-queue: ${PAYMENT_APROVED_QUEUE:payment-aproved-ms-pix}
  payment-expired-queue: ${PAYMENT_EXPIRED_QUEUE:payment-expired-ms-pix}
  payment-aproved-routingKey: ${PAYMENT_APROVED_ROUTINGKEY:status-pix-paid}
  payment-expired-routingKey: ${PAYMENT_EXPIRED_ROUTINGKEY:status-pix-expired}
  deadLetter-exchange: ${DEADLETTER_EXCHANGE:payment-status-dlx.ex}
  payment-aproved-queue-dlq: ${PAYMENT_APROVED_QUEUE_DLQ:payment-aproved.dlq}
  payment-expired-queue-dlq: ${PAYMENT_EXPIRED_QUEUE_DLQ:payment-expired.dlq}
